/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const Video = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'videoFile' : ExternalBlob,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'joinTimestamp' : Time,
  'totalViews' : IDL.Nat,
  'followers' : IDL.Nat,
  'following' : IDL.Nat,
});
export const Comment = IDL.Record({
  'id' : IDL.Text,
  'username' : IDL.Text,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'videoId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'addView' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createVideo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), ExternalBlob],
      [IDL.Text],
      [],
    ),
  'deleteComment' : IDL.Func([IDL.Text], [], []),
  'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentsByVideo' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getTrendingVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideo' : IDL.Func([IDL.Text], [IDL.Opt(Video)], ['query']),
  'getVideosByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Video)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isMonetizationEligible' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'likeVideo' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const Video = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'videoFile' : ExternalBlob,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'joinTimestamp' : Time,
    'totalViews' : IDL.Nat,
    'followers' : IDL.Nat,
    'following' : IDL.Nat,
  });
  const Comment = IDL.Record({
    'id' : IDL.Text,
    'username' : IDL.Text,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'videoId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'addView' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createVideo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), ExternalBlob],
        [IDL.Text],
        [],
      ),
    'deleteComment' : IDL.Func([IDL.Text], [], []),
    'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentsByVideo' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getTrendingVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideo' : IDL.Func([IDL.Text], [IDL.Opt(Video)], ['query']),
    'getVideosByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Video)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isMonetizationEligible' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'likeVideo' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };